src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 * @ORM\Table(name="categories")
 */
class Category
{
    public  const FULL_TIME_TYPE='full-time';
    public  const PART_TIME_TYPE='part-time';
    public  const FREELANCE_TYPE='freelance';

    public const TYPES=[
        self::FULL_TIME_TYPE,
        self::PART_TIME_TYPE,
        self::FREELANCE_TYPE,
    ];


    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=128, unique=true)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=128, unique=true)
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $name;

    /**
     * @var Job[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Job", mappedBy="category")
     */
    private $jobs;

    /**
     * @var Affiliate[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Affiliate", mappedBy="categories")
     */
    private $affiliates;

    public function __construct()
    {
        $this->jobs = new ArrayCollection();
        $this->affiliates = new ArrayCollection();
    }

    /**
     * @return string|null
     */
    public function getSlug() : ?string
    {
        return $this->slug;
    }

    /**
     * @param  string $slug
     */
    public function setSlug(string $slug) : void
    {
        $this->slug=$slug;
    }

    /**
     * @return int
     */
    public function getId() : ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName() : ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return self
     */
    public function setName(string $name) : self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Job[]|ArrayCollection
     */
    public function getJobs()
    {
        return $this->jobs;
    }

    /**
     * @return Job[]|ArrayCollection
     */
    public function getActiveJobs()
    {
        return $this->jobs->filter(function(Job $job) {
            return $job->getExpiresAt() > new \DateTime();
        });
    }

    /**
     * @param Job $job
     *
     * @return self
     */
    public function addJob(Job $job) : self
    {
        if (!$this->jobs->contains($job)) {
            $this->jobs->add($job);
        }

        return $this;
    }

    /**
     * @param Job $job
     *
     * @return self
     */
    public function removeJob(Job $job) : self
    {
        $this->jobs->removeElement($job);

        return $this;
    }

    /**
     * @return Affiliate[]|ArrayCollection
     */
    public function getAffiliates()
    {
        return $this->affiliates;
    }

    /**
     * @param Affiliate $affiliate
     *
     * @return self
     */
    public function addAffiliate($affiliate) : self
    {
        if (!$this->affiliates->contains($affiliate)) {
            $this->affiliates->add($affiliate);
        }

        return $this;
    }

    /**
     * @param Affiliate $affiliate
     *
     * @return self
     */
    public function removeAffiliate($affiliate) : self
    {
        $this->affiliates->removeElement($affiliate);

        return $this;
    }
}

src/Form/JobType.php
<?php
namespace App\Form;

use App\Entity\Category;
use App\Entity\Job;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Validator\Constraints\Email;


class JobType extends AbstractType{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type', ChoiceType::class, [
                'choices' => array_combine(Job::TYPES, Job::TYPES),
                'expanded' => true,
                'constraints'=>[
                    new NotBlank()
                ]
            ])
            ->add('company', TextType::class, [
                'constraints'=>[
                    new NotBlank(),
                    new Length(['max'=>255])
                ]
            ])
            ->add('logo', TextType::class, [
                'data_class' => null,
                'required' => false,
                'constraints' => [
                    new Image()
                ]
            ])
            ->add('url', UrlType::class,[
                'required'=>false,
                'constraints'=>[
                    new Length(['max'=>255])
                ]
            ])
            ->add('position', TextType::class,[
                'required'=>false,
                'constraints'=>[
                    new Length(['max'=>255])
                ]
            ])
            ->add('location', TextType::class, [
                'required'=>false,
                'constraints'=>[
                    new Length(['max'=>255])
                ]
            ])
            ->add('description', TextareaType::class, [
                'required'=>false,
                'constraints'=>[
                    new NotBlank()
                ]
            ])
            ->add('howToApply', TextType::class, [
                'label' => 'How to apply?',
            ])
            ->add('public', ChoiceType::class, [
                'choices'  => [
                    'Yes' => true,
                    'No' => false,
                ],
                'label' => 'Public?',
            ])
            ->add('activated', ChoiceType::class, [
                'choices'  => [
                    'Yes' => true,
                    'No' => false,
                ],
                'constraints'=>[
                    new NotNull()
                ]
            ])
            ->add('email', EmailType::class,[
                'constraints'=>[
                    new NotBlank(),
                    new Email()
                ]
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'constraints'=>[
                    new NotBlank(),
                ]
            ]);
            /**->add('token', TextType::class, [
                'constraints'=>[
                    new NotBlank(),
                    new Length(['max'=>255])
                ]
            ]);
            */
    }
        public function configureOptions(OptionsResolver $resolver){
            $resolver->setDefaults([
                'data_class'=>Job::class
            ]);
        }

}

src/Controller/JobController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Job;
use App\Form\JobType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use App\Service\FileUploader;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class JobController extends AbstractController
{
    /**
     *
     * @Route("/", name="job.list", methods="GET")
     *
     * @param EntityManagerInterface $em
     *
     * @return Response
     */
    public function list(EntityManagerInterface $em) : Response
    {
        $categories = $em->getRepository(Category::class)->findWithActiveJobs();
        return $this->render('job/list.html.twig', [
            'categories' => $categories,
        ]);
    }
    /**
     *
     * @Route("job/{id}", name="job.show", methods="GET", requirements={"id" = "\d+"})
     *
     * @Entity("job", expr="repository.findActiveJob(id)")
     *
     * @param Job $job
     *
     * @return Response
     */
    public function show(Job $job) : Response
    {
        $deleteForm = $this->createDeleteForm($job);
        return $this->render('job/show.html.twig', [
            'job' => $job,
            'deleteForm' => $deleteForm->createView(),
        ]);
    }
    /**
     *
     * @Route("/job/create", name="job.create", methods={"GET", "POST"})
     *
     * @param Request $request
     * @param EntityManagerInterface $em
     *
     * @return RedirectResponse|Response
     */
    public function create(Request $request, EntityManagerInterface $em) : Response
    {
        $job = new Job();
        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($job);
            $em->flush();
            return $this->redirectToRoute(
                'job.preview',
                ['token' => $job->getToken()]
            );
        }
        return $this->render('job/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    /**
     *
     * @Route("/job/{token}/edit", name="job.edit", methods={"GET", "POST"}, requirements={"token" = "\w+"})
     *
     * @param Request $request
     * @param Job $job
     * @param EntityManagerInterface $em
     *
     * @return Response
     */
    public function edit(Request $request, Job $job, EntityManagerInterface $em) : Response
    {
        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirectToRoute(
                'job.preview',
                ['token' => $job->getToken()]
            );
        }
        return $this->render('job/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    /**
     *
     * @Route("job/{token}", name="job.preview", methods="GET", requirements={"token" = "\w+"})
     *
     * @param Job $job
     *
     * @return Response
     */
    public function preview(Job $job) : Response
    {
        $deleteForm = $this->createDeleteForm($job);
        return $this->render('job/show.html.twig', [
            'job' => $job,
            'hasControlAccess' => true,
            'deleteForm' => $deleteForm->createView(),
        ]);
    }
    /**
     *
     * @Route("job/{token}/delete", name="job.delete", methods="DELETE", requirements={"token" = "\w+"})
     *
     * @param Request $request
     * @param Job $job
     * @param EntityManagerInterface $em
     *
     * @return Response
     */
    public function delete(Request $request, Job $job, EntityManagerInterface $em) : Response
    {
        $form = $this->createDeleteForm($job);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->remove($job);
            $em->flush();
        }
        return $this->redirectToRoute('job.list');
    }
    /**
     *
     * @param Job $job
     *
     * @return FormInterface
     */
    private function createDeleteForm(Job $job) : FormInterface
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('job.delete', ['token' => $job->getToken()]))
            ->setMethod('DELETE')
            ->getForm();
    }
}

templates/job/control_panel.html.twig
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <span class="navbar-brand"> Panneau de contrôle </span>
        </div>
        <div class="collapse navbar-collapse">
            {{ form_start(deleteForm, {'attr':{'class':'navbar-form navbar-left' }}) }}
                {{ form_widget(deleteForm)}}
                    <button type="submit" class="btn btn-default" onclick="return confirm('Etes-vous sûr ?')">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        Delete
                    </button>
            {{ form_end(deleteForm) }}

            {%  if job.activated %}
                {% if job.expiresAt < date() %}
                    <p class="navbar-text"> Expiré </p>
                {%  else %}
                    <p class="navbar-text"> Expire dans
                        <strong>{{ job.expiresAt.diff(date())|date('%a') }}</strong>
                        jours
                    </p>
                {% endif %}

                {% if job.expiresAt.diff(date())|date('%a') < 5 %}
                    <a class="btn btn-default navbar-btn" href="#">
                        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                        Prolonger de 30 jours
                    </a>
                {% endif %}
            {% else %}
                <a class="btn btn-default navbar-btn" href="{{path('job.edit',{'token':job.token})}}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>Edition
                </a>
                {#<a class="btn btn-default navbar-btn" href="#">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true">Publication</span>
                </a>#}
            {% endif %}

            <p class="navbar-text navbar-right">
                [Mettre en bookmark <a href="{{ url('job.preview', {'token':job.token}) }}">URL</a> pour pouvoir le gérer]
            </p>
        </div>
    </div>
</nav>

templates/job/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1> création d'un job </h1>
    {# {{ form_start(form, {'attr':{'novalidate':'novalidate'}})}} #}
   {{ form_start(form)}}
        {{ form_widget(form) }}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Creation</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/job/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1> Edition d'un job </h1>
    {# {{ form_start(form, {'attr':{'novalidate':'novalidate'}})}} #}
    {{ form_start(form)}}
    {{ form_widget(form) }}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Editer</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/job/list.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% for category in categories %}
        <h4>
            <a href="{{ path('category.show', {slug:category.slug}) }}">{{ category.name }}</a>
        </h4>
        {% include 'job/table.html.twig' with {'jobs':category.activeJobs|slice(0, max_jobs_on_homepage)} only %}
    {% endfor %}
{% endblock %}

templates/job/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{#{% if hasControlAccess is defined and hasControlAccess %}#}
        {% include 'job/control_panel.html.twig' with {
            'job': job,
            'deleteForm': deleteForm
        } only %}
{#{% endif %}#}
    <h1>annonces</h1>

    <div class="media" style="margin-top: 60px;">
        {% if job.logo %}
            <div class="media-left">
                <a href="{{ job.url }}" target="_blank">
                    <img class="media-object" style="width:100px; height:100px;" src="{{ asset(jobs_web_directory ~ '/' ~ job.logo.filename) }}">
                </a>
            </div>
        {% endif %}

        <div class="media-body">
            <div class="row">
                <div class="col-sm-10">
                    <h3 class="media-heading"><strong>{{ job.company }}</strong> <i>({{ job.location }})</i></h3>
                </div>

                <div class="col-sm-2">
                    <i class="pull-right">Posté le {{ job.createdAt|date('m/d/Y') }}</i>
                </div>
            </div>

            <p>
                <strong>{{ job.position }}</strong>
                <small> - <i>{{ job.type }}</i></small>
            </p>

            <p>{{ job.description|nl2br }}</p>

            <p style="margin-top: 40px;">
                <strong>Comment Candidater ?</strong>
            </p>

            <p>{{ job.howToApply }}</p>

            <div class="row">
                <div class="col-sm-12 text-right">
                    <a class="btn btn-default" href="{{ path('job.list') }}">
                        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                        Retour à la liste
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/job/table.html.twig
<table class="table text-center">
    <thead>
    <tr>
        <th class="active text-center">City</th>
        <th class="active text-center">Position</th>
        <th class="active text-center">Company</th>
    </tr>
    </thead>
    <tbody>
    {% for job in jobs %}
        <tr>
            <td>{{ job.location }}</td>
            <td>
                <a href="{{ path('job.show', {id: job.id}) }}">
                    {{ job.position }}
                </a>
            </td>
            <td>{{ job.company }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>